version: "3.8"

services:
  pg_database:
    container_name: postres
    image: postgres:13-alpine
    ports:
      - "5439:5432" # Change if you like! 5439 is external to container
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: "postgres -c max_connections=150
              -c shared_buffers=512MB -c effective_cache_size=1536MB
              -c maintenance_work_mem=128MB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB
              -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200
              -c work_mem=3495kB -c min_wal_size=1GB -c max_wal_size=4GB -c max_worker_processes=2
              -c max_parallel_workers_per_gather=1 -c max_parallel_workers=2 -c max_parallel_maintenance_workers=1"
    env_file:
      - '.env'
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  django-app:
    container_name: django-app
    image: django-app
    ports:
      - "7000:7000"
    build:
      context: ./web
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:7000
    restart: always
    links:
      - "pg_database"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

# Uncomment the following lines if you want to use a volume for the database
volumes:
  pgdata: { }
  cache: { }
