# Generated by Django 5.0.2 on 2024-03-04 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True, verbose_name='Диаметр')),
            ],
            options={
                'verbose_name': 'Диаметр',
                'verbose_name_plural': 'Диаметры',
                'db_table': 'diameters',
            },
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True, verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Высота',
                'verbose_name_plural': 'Высоты',
                'db_table': 'heights',
            },
        ),
        migrations.CreateModel(
            name='Width',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True, verbose_name='Ширина')),
            ],
            options={
                'verbose_name': 'Ширина',
                'verbose_name_plural': 'Ширины',
            },
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('tire_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID шины')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд, модель')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('season', models.CharField(choices=[('W', 'Зима'), ('S', 'Лето'), ('A', 'Всесезонные')], max_length=1, verbose_name='Сезонность')),
                ('load_index', models.IntegerField(blank=True, null=True, verbose_name='Индекс нагрузки')),
                ('speed_rating', models.CharField(blank=True, max_length=3, null=True, verbose_name='Индекс скорости')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Скидка, %')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tires/', verbose_name='Изображение')),
                ('feedback', models.URLField(blank=True, max_length=255, null=True, verbose_name='Отзывы')),
                ('image_telegram_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID изображения в Telegram')),
                ('diameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.diameter', verbose_name='Диаметр')),
                ('height', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.height', verbose_name='Высота')),
                ('width', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.width', verbose_name='Ширина')),
            ],
            options={
                'verbose_name': 'Шина',
                'verbose_name_plural': 'Шины',
                'db_table': 'tires',
            },
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
