# Generated by Django 5.0.2 on 2024-03-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_cartitem_order_orderitem_delete_user'),
        ('rest_api', '0003_diameter_height_width_tire_delete_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Елемент Заказа', 'verbose_name_plural': 'Елементы Заказа'},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'order_id')},
        ),
    ]
